# Generated by Django 5.1.2 on 2024-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatatable',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='sensortable',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
    ]
